name    'andschwa-person'
version '0.0.2'
source  'git://github.com/andschwa/puppet-person.git'
author  'Andrew Schwartzmeyer'
license 'MIT License'
summary 'Person setup module'
description 'Puppet module for setting up a "person" with fresh dotfiles and an emacs.d (highly specialized)'
project_page 'https://github.com/andschwa/puppet-person'

dependency 'puppetlabs/vcsrepo', '>= 0.2.0'
dependency 'arnoudj/sudo', '>= 0.3.0'
dependency 'andschwa/dotfiles', '>= 0.0.1'
